# Bio-Inspired MARL Experiment Configuration
# 3D Brain-inspired Multi-Agent Framework

experiment_name: "bio_inspired_marl_baseline"
description: "Baseline experiment for 3D brain-inspired multi-agent coordination"

# Grid Configuration
grid_size: [4, 3, 3]  # 4x3x3 grid
total_agents: 30      # 27 regular + 3 coordinators
num_coordinators: 3

# Training Parameters
training:
  total_episodes: 1000
  max_steps_per_episode: 500
  learning_rate: 0.001
  batch_size: 32
  gradient_clip: 1.0
  
# Agent Configuration
agents:
  regular:
    hidden_dim: 256
    communication_range: 2.0
    memory_capacity: 100
    
  coordinator:
    hidden_dim: 512
    communication_range: 4.0
    memory_capacity: 200
    supervision_radius: 3.0

# Neural Network Architecture
networks:
  pheromone_attention:
    hidden_dim: 256
    num_heads: 8
    dropout: 0.1
    
  neural_plasticity:
    hidden_dim: 256
    memory_retention_bias: 0.1
    adaptive_plasticity: true
    
  compression:
    input_dim: 256
    compressed_dim: 128
    compression_ratio: 0.5

# Shared Memory System
memory:
  vector_dim: 256
  max_vectors: 1000
  compression_enabled: true
  ttl_seconds: 300
  cleanup_interval: 60

# Communication Protocol
communication:
  max_queue_size: 1000
  message_ttl: 30
  retry_attempts: 3
  bandwidth_limit: 100

# Breakthrough Detection
breakthrough_detection:
  threshold: 0.7
  types:
    - pattern_recognition
    - coordination_improvement
    - efficiency_gain
    - novel_strategy
    - communication_protocol
    - memory_optimization
    - spatial_awareness
  
  sharing_threshold: 0.8
  validation_required: true

# Environment Configuration
environment:
  name: "puzzle_coordination"
  difficulty: "medium"
  reward_structure:
    individual_breakthrough: 10.0
    shared_breakthrough: 15.0
    coordination_success: 5.0
    communication_efficiency: 1.0
    memory_utilization: 0.5
  
  termination_conditions:
    max_steps: 500
    success_threshold: 0.9
    timeout_episodes: 50

# Visualization Settings
visualization:
  enabled: true
  update_interval: 0.5
  export_format: "json"
  
  3d_grid:
    auto_rotate: false
    show_grid: true
    animation_speed: 1.0
    
  communication_flow:
    show_arrows: true
    flow_animation: true
    intensity_scaling: true
    
  memory_heatmap:
    color_scheme: "viridis"
    update_frequency: 2.0
    show_access_patterns: true

# Logging and Monitoring
logging:
  level: "INFO"
  output_dir: "./logs"
  metrics_interval: 10
  
  tracked_metrics:
    - communication_efficiency
    - breakthrough_frequency
    - memory_utilization
    - coordination_success_rate
    - network_clustering
    - spatial_coverage
    - information_flow_rate

# Checkpointing
checkpointing:
  enabled: true
  interval: 100
  max_checkpoints: 10
  output_dir: "./checkpoints"
  
  save_components:
    - model_state
    - optimizer_state
    - memory_state
    - communication_patterns
    - breakthrough_history

# Performance Optimization
performance:
  parallel_agents: true
  batch_communication: true
  memory_optimization: true
  gpu_acceleration: true
  
  threading:
    max_workers: 4
    communication_threads: 2
    visualization_threads: 1

# Experimental Variants
variants:
  baseline:
    description: "Standard configuration"
    
  high_communication:
    description: "Increased communication range and frequency"
    agents:
      regular:
        communication_range: 3.0
      coordinator:
        communication_range: 5.0
    
  memory_focused:
    description: "Larger memory capacity and enhanced sharing"
    memory:
      max_vectors: 2000
      compression_ratio: 0.3
    agents:
      regular:
        memory_capacity: 200
      coordinator:
        memory_capacity: 400
    
  breakthrough_intensive:
    description: "Lower breakthrough threshold for more frequent events"
    breakthrough_detection:
      threshold: 0.5
      sharing_threshold: 0.6

# Advanced Features
advanced:
  evolutionary_optimization:
    enabled: false
    population_size: 20
    mutation_rate: 0.1
    
  transfer_learning:
    enabled: false
    source_experiment: ""
    transfer_components: ["attention", "memory"]
    
  meta_learning:
    enabled: false
    adaptation_steps: 5
    meta_lr: 0.01
    
  curriculum_learning:
    enabled: false
    stages:
      - name: "basic_coordination"
        episodes: 200
        difficulty: 0.3
      - name: "advanced_coordination"
        episodes: 500
        difficulty: 0.7
      - name: "expert_coordination"
        episodes: 300
        difficulty: 1.0

# Deployment Configuration
deployment:
  mode: "development"  # development, production, research
  
  development:
    debug: true
    profiling: true
    mock_data: false
    
  production:
    debug: false
    profiling: false
    optimization: "speed"
    
  research:
    debug: false
    profiling: true
    detailed_logging: true
    export_all_data: true
